name: React Build File

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build React App
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: build command
        run: npm run build
      - name: deploy to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel deploy --prebuilt --confirm --token $VERCEL_TOKEN
