name: Preview Deploy

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: build command
        run: npm run build
      - name: deploy to vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --yes --token $VERCEL_TOKEN
